### ISSUE TITLE
[Site] Favicon needs updated to GetNighthawk logo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#100]
**Current State of the GetNighthawk.dev site**
Currently, the favicon on getnighthawk.dev is that of Meshery's logo.

**Desired State of the GetNighthawk.dev site**
The GetNighthawk logo should be used instead. Find the GetNighthawk logo here - https://layer5.io/brand

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Anita-ihuman** [comment]
I will like to take this up.
