### ISSUE TITLE
[Site] Add links to GetNighthawk mailing lists

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#101]
**Current Behavior**
Project mailing lists exist, but are not shown on the site.

**Desired Behavior**

These lists should be available for anyone to join:

- [Users](https://groups.google.com/a/getnighthawk.dev/g/users)
- [Developers(https://groups.google.com/a/getnighthawk.dev/g/developers)
- [Maintainers](https://groups.google.com/a/getnighthawk.dev/g/maintainers)

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by leecalcote** [comment]
@austinogiza will you supply a mockup for where these lists should be placed?

**Comment by austinogiza** [comment]
@leecalcote here it is  https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5884%3A12909

**Comment by akashc777** [comment]
Hi  @leecalcote,
can work on this?

**Comment by leecalcote** [comment]
That would be great. Yes, @akashc777

**Comment by akashc777** [comment]
please can I get access to the Figma file @leecalcote @austinogiza

**Comment by austinogiza** [comment]
@akashc777  Just sent it

**Comment by akashc777** [comment]
<img width="570" alt="Screenshot 2021-05-14 at 12 27 10 AM" src="https://user-images.githubusercontent.com/32003795/118173405-228aca00-b44b-11eb-9453-1f3e7eb59eb9.png">
This right ?

**Comment by leecalcote** [comment]
https://layer5.io/brands - has the latest, bird-looking logo, which is the correct one. I think @austinogiza has a more condensed version of this footer mockup, but I'm not sure... @austinogiza?

**Comment by akashc777** [comment]
@leecalcote I can add CSS/SCSS files while adding the mailing list section right?

**Comment by leecalcote** [comment]
Right, yes. ✔️

**Comment by austinogiza** [comment]
@akashc777  Apologize for that, I have updated the figma file to reflect the logo on the current website, sorry for the confusion

**Comment by akashc777** [comment]
@austinogiza I got confused since the alignment on the live site is different than in the Figma prototype (looks better in Figma i think some CSS issue on live site ).

Btw where can I find the designs for mobile view?

sorry for too many questions 😅

**Comment by austinogiza** [comment]
@akashc777  I will provide the mobile view shortly, do hit me up on slack so I notify you when they are done
