### ISSUE TITLE
[README] Update README Community Section

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/getnighthawk#104]
**Description**
The Community section in the README says "Access the Community Drive". There is a new procedure of having this automated based on the individual filling in a [community member form](https://layer5.io/newcomer)

**Expected Behavior**
Update "Access Community Drive" to "To Access Community Drive, fill Community Member Form"

**Screenshots**
![img](https://user-images.githubusercontent.com/62384659/117368468-7cbfe400-aebb-11eb-92c2-0033fd74bcfc.png)

**Environment:**

- OS: [e.g. Ubuntu]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
- Device: [e.g. laptop, iPhone 8]

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Harshita-Kanal** [comment]
Can I take this up?

**Comment by Anita-ihuman** [comment]
Yes, you can
