### ISSUE TITLE
[Site] Live site needs to match with the design

### ISSUE THREAD

**Issue by akashc777** [layer5io/getnighthawk#108]
**Current State of the GetNighthawk.dev site**
A brief description of what the problem is.

The background colors, alignment, and spacing doesn't match the design

eg.
<img width="1092" alt="Screenshot 2021-05-14 at 5 46 58 AM" src="https://user-images.githubusercontent.com/32003795/118202544-cf7b3c00-b477-11eb-8572-6428e893892e.png">

**Desired State of the GetNighthawk.dev site**
A brief description of the change you are requesting.

Matching all the alignments, colors, and spacing with the design https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5884%3A12909

eg.
<img width="807" alt="Screenshot 2021-05-14 at 5 22 28 AM" src="https://user-images.githubusercontent.com/32003795/118202676-0cdfc980-b478-11eb-940a-40907307f6d4.png">

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by leecalcote** [comment]
Thanks, @akashc777

**Comment by akashc777** [comment]
Hi @leecalcote ,
I will wait for my previous PR to get merged since it will give me an idea if I need to make some improvements in my coding style or I should follow any best practices.  Before making some major changes here 😅.  

I will start working on this as soon as my 1st PR gets merged 🕺🏼.

**Comment by leecalcote** [comment]
// @austinogiza @vinayaksh42

**Comment by vinayaksh42** [comment]
Hey @akashc777 , Your 1st PR has been recently merged. Would you like to work on this issue now?

**Comment by akashc777** [comment]
Thanks @vinayaksh42 for the mention. I got held up with interviews. I will make a PR within 1-2 days from now

**Comment by JubayerJoy** [comment]
@akashc777 will not be with us [for some time](https://github.com/layer5io/getnighthawk/pull/117#issuecomment-851013194).
Anyone interested can take the issue.

**Comment by NikhilSharma03** [comment]
@JubayerJoy Can I work on this??

**Comment by JubayerJoy** [comment]
@NikhilSharma03 Sure!
Please check the [previous PR](https://github.com/layer5io/getnighthawk/pull/117) of @akashc777 for reusing some of the work done.

**Comment by Jashpatel1** [comment]
Any progress here @JubayerJoy @NikhilSharma03

**Comment by NikhilSharma03** [comment]
@Jashpatel1 I think this issue was recreated and is in progress by Anita-ihuman. Let me know if I have to work on this issue.
Thank you.

**Comment by Jashpatel1** [comment]
Closing with #129
