### ISSUE TITLE
[Site] Background color change

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#110]
**Current State of the GetNighthawk.dev site**
Currently, the hero section of the website as well as the "what is getnighthawk?" section has a grey background color.
check it out at - https://getnighthawk.dev/
![chrome_Yd4XuBEZPf](https://user-images.githubusercontent.com/54861487/118651052-be795480-b802-11eb-8af5-682eda438347.png)

**Desired State of the GetNighthawk.dev site**
The Figma design is a bit different for the hero section as it has a blue tone background color #C9FCF6. The "what is getnighthawk?" section is supposed to have a white background like all the other sections, instead of grey.
![chrome_DrufrQo7Ga](https://user-images.githubusercontent.com/54861487/118651337-0ef0b200-b803-11eb-984c-f45d6d28d52d.png)

Figma design link - https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5884%3A12909

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by NikhilSharma03** [comment]
Can you assign this issue to me?

**Comment by vinayaksh42** [comment]
Sure @NikhilSharma03
