### ISSUE TITLE
[Site] Stewarded by and Organized by section

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#111]
**Current State of the GetNighthawk.dev site**
Currently, there are two different independent sections for Stewarded by and Organized by.
![chrome_YJ3m6LxVeQ](https://user-images.githubusercontent.com/54861487/118651677-70188580-b803-11eb-838b-c095214e3541.png)

**Desired State of the GetNighthawk.dev site**
The Figma design has both of these sections combined into one single section.
![chrome_0yvlclrxEi](https://user-images.githubusercontent.com/54861487/118651799-8888a000-b803-11eb-8e00-5d90267641f6.png)

Figma design link - https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5046%3A0

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Anita-ihuman** [comment]
Can I take up this issue?

**Comment by vinayaksh42** [comment]
> Can I take up this issue?

Sure
