### ISSUE TITLE
Typo in the CONTRIBUTING.md

### ISSUE THREAD

**Issue by Ayush-Khandelwal-007** [layer5io/getnighthawk#112]
Just a small typo in the steps to build GetNightHawk site.Step 3 is merged with Step 2.

- See the [CONTRIBUTING.md](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
![Screenshot 2021-05-18 at 6 45 48 PM](https://user-images.githubusercontent.com/59086855/118659116-a9a0bf00-b80a-11eb-8217-504b770d69b7.png)

**Comment by vinayaksh42** [comment]
Hey @Ayush-Khandelwal-007 would you like to take this issue?

**Comment by Ayush-Khandelwal-007** [comment]
Sure!
