### ISSUE TITLE
[Site] Footer re-work and Mobile responsiveness

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#116]
**Current State of the GetNighthawk.dev site**
Currently, The footer has a few components (copyright text and social media logos) that are wrongly aligned in the desktop view as well as the mobile view.
![chrome_fuT4082djy](https://user-images.githubusercontent.com/54861487/118937060-c18f5480-b96a-11eb-9d8f-43ddae0bfe06.png)
![chrome_nb33r6vaV6](https://user-images.githubusercontent.com/54861487/118937065-c2c08180-b96a-11eb-9d19-8c07a28cc840.png)

**Desired State of the GetNighthawk.dev site**
Refer to the Figma link - https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=6189%3A0

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Anita-ihuman** [comment]
can I take up this issue?
