### ISSUE TITLE
Project set up Step not updated.

### ISSUE THREAD

**Issue by Ayush-Khandelwal-007** [layer5io/getnighthawk#118]
The command to add upstream remote locally is still not updated as per this repo.

### **Present State**
Text in red box should be updated I guess.

![Screenshot 2021-05-26 at 8 41 28 PM](https://user-images.githubusercontent.com/59086855/119685893-67f3c200-be63-11eb-9395-2e7f270acb9d.png)

#### [**Link to the document**](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING-gitflow.md)

**Comment by leecalcote** [comment]
Thanks, @Ayush-Khandelwal-007 👍
