### ISSUE TITLE
[Site] Fix Padding and Margins 

### ISSUE THREAD

**Issue by Jashpatel1** [layer5io/getnighthawk#123]
**Current State of the GetNighthawk.dev site**
Currently, the [site](https://getnighthawk.dev/) has unnecessary whitespaces which can be updated.

**Desired State of the GetNighthawk.dev site**
The [Figma Design](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=6189%3A0) can be helpful to fix those whitespaces by changing margins and paddings throughout the site.

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by DARK-art108** [comment]
Can I work upon this? Can you guide a more little bit! 
How to open in figma! And fix those things :)

**Comment by Jashpatel1** [comment]
> Can I work upon this? Can you guide a more little bit!
> How to open in figma! And fix those things :)

Yaa sure, please go ahead.

**Comment by DARK-art108** [comment]
@Jashpatel1 When I open the Figma design link from above the link is not opening! Showing file not found!
https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=6189%3A0 This one!

**Comment by vinayaksh42** [comment]
> @Jashpatel1 When I open the Figma design link from above the link is not opening! Showing file not found!
> https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=6189%3A0 This one!
@DARK-art108 I think Figma initially requires an invite via email. It would be really great if you can join the slack workspace of Layer5 http://slack.layer5.io/ 
Message me your email and I will send you an invite.

**Comment by DARK-art108** [comment]
Yes sure! @sayantan1413

**Comment by sayantan1413** [comment]
Are you there in the slack group then we can discuss a little?

**Comment by DARK-art108** [comment]
Yes I am their in slack group! Ping me anytime :)

**Comment by sayantan1413** [comment]
Hey @Jashpatel1 and @DARK-art108 I fixed the unnecessary whitespaces. Can you give me any suggestions about what more to change.

https://user-images.githubusercontent.com/64970095/121347473-dd23c480-c944-11eb-92a3-6e4755f8ddf0.mp4

**Comment by Jashpatel1** [comment]
> Hey @Jashpatel1 and @DARK-art108 I fixed the unnecessary whitespaces. Can you give me any suggestions about what more to change.
> 
>  getnighthawk.modified.mp4

Looks good @sayantan1413 . You can go ahead and send a PR on this. Will let you know in the review if any changes are required.

**Comment by DARK-art108** [comment]
Awesome @sayantan1413 It Looks Good!
