### ISSUE TITLE
[Site] Change color and style of menu items 

### ISSUE THREAD

**Issue by JubayerJoy** [layer5io/getnighthawk#124]
**Current State of the GetNighthawk.dev site**
The current implementation of the following sections should be corrected to follow the design specification:
1. the FAQs section of [getnighthawk.dev](https://getnighthawk.dev/)

![FAQs](https://user-images.githubusercontent.com/31549564/120231551-74b55300-c273-11eb-95b3-ab262bdfb562.png)

2. The sidebar of [Getnighthawk Docs](https://getnighthawk.dev/docs)

![Docs SideNav](https://user-images.githubusercontent.com/31549564/120231651-a3332e00-c273-11eb-8532-df17a80ac8da.png)

**Desired State of the GetNighthawk.dev site**

The design should be similar to this for the FAQs section: 
![FAQs](https://user-images.githubusercontent.com/31549564/120231746-e42b4280-c273-11eb-812c-7bc7c8c61ff3.png)

Similar design should also be implemented for the Docs side-navbar.

For convenience, you can check out the [Figma design](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs).

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by NikhilSharma03** [comment]
Can i work on this @JubayerJoy

**Comment by soham4abc** [comment]
Figma file not visible

**Comment by soham4abc** [comment]
Need permission for the Figma files

**Comment by NikhilSharma03** [comment]
![Screenshot from 2021-06-01 19-11-57](https://user-images.githubusercontent.com/58226527/120333537-6ca9f180-c30d-11eb-86ed-ed11c61338a6.png)
@JubayerJoy Are the colors are correct?

**Comment by JubayerJoy** [comment]
Hi @NikhilSharma03, it looks correct to me but will be sure after you open a PR.
Thank you 🎈

**Comment by NikhilSharma03** [comment]
Thank you @JubayerJoy for assigning the issue. Yes, Definetly 👍

**Comment by JubayerJoy** [comment]
@soham4abc, Figma has changed its policy for teams for which the permission is limited.
If you need the design files, kindly reach out on [slack](http://slack.layer5.io/).

Thank you!

**Comment by soham4abc** [comment]
> @soham4abc, Figma has changed its policy for teams for which the permission is limited.
> If you need the design files, kindly reach out on [slack](http://slack.layer5.io/).
> 
> Thank you!

I am on slack!! I requested for permission in the general chat!
