### ISSUE TITLE
[Site] Update footer style

### ISSUE THREAD

**Issue by NikhilSharma03** [layer5io/getnighthawk#135]
**Current State of the GetNighthawk.dev site**
The current footer ul style can be improved.

- Current style

![Screenshot from 2021-06-12 18-38-56](https://user-images.githubusercontent.com/58226527/121777183-596d1080-cbae-11eb-9c20-3516e1fc799d.png)

**Desired State of the GetNighthawk.dev site**
We can update the footer style.

- Changes we can make

## Elements aligned in the center

![Screenshot from 2021-06-12 18-38-31](https://user-images.githubusercontent.com/58226527/121777224-9c2ee880-cbae-11eb-89b7-dad8dacfc16f.png)

## Elements aligned in the Left

![Screenshot from 2021-06-12 18-40-33](https://user-images.githubusercontent.com/58226527/121777235-a8b34100-cbae-11eb-8922-698d2d15b2fc.png)

# Note for reviewers
If any of these styles look good and can be used. Feel free to assign this issue to me. Thank you.

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by NikhilSharma03** [comment]
@leecalcote Can you please review?

**Comment by vinayaksh42** [comment]
@NikhilSharma03 the center-aligned style is looking much better than what we have right now. @leecalcote what's your opinion on this?

**Comment by NikhilSharma03** [comment]
@vinayaksh42 Should I start working on it?

**Comment by vinayaksh42** [comment]
> @vinayaksh42 Should I start working on it?

let's wait for @leecalcote's opinion, Also make sure that the format of the footer remains unaffected in desktop view

**Comment by NikhilSharma03** [comment]
Yeah Sure

**Comment by NikhilSharma03** [comment]
@vinayaksh42 I have made a PR. Let me know if the changes got approved. I will link this issue in the PR. Thank you.
