### ISSUE TITLE
[Site] Improve legibility of Answers test in FAQs

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#137]
**Current State of the GetNighthawk.dev site**
The FAQs answers are a bit light and difficult to read on the white background.

**Desired State of the GetNighthawk.dev site**
Ideally, this text is slightly larger and slightly darker.

<img width="767" alt="Screen Shot 2021-06-15 at 11 43 35 AM" src="https://user-images.githubusercontent.com/7570704/122092009-1047d700-cdcf-11eb-980b-203b60768bab.png">

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by NikhilSharma03** [comment]
@leecalcote Can i work on this issue?

**Comment by leecalcote** [comment]
That would be great, @NikhilSharma03 👍
