### ISSUE TITLE
Update the Logo on Home page.

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/getnighthawk#138]
**Current State of the GetNighthawk.dev site**

The current logo on the Getnighthawk home page is the same as the navbar logo.

![Screenshot 2021-06-15 at 21 19 19](https://user-images.githubusercontent.com/62384659/122118072-8aa04780-ce1f-11eb-8fac-e1917c80664e.png)

**Desired State of the GetNighthawk.dev site**

the logo on the Getnigthawk home page should be updated to look like this.

![Screenshot 2021-06-15 at 21 22 19](https://user-images.githubusercontent.com/62384659/122118317-cc30f280-ce1f-11eb-80b1-1a3b8f1dd147.png)

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by leecalcote** [comment]
Excellent!

**Comment by NikhilSharma03** [comment]
@Anita-ihuman Can I work on this issue? If that's okay let me know where can I find the new logo image.
