### ISSUE TITLE
Update the Site home page

### ISSUE THREAD

**Issue by Anita-ihuman** [layer5io/getnighthawk#142]
**Current State of the GetNighthawk.dev site**
The changes to the  "what is Getnighthawk"component were reverted.

![Screenshot 2021-06-17 at 22 07 34](https://user-images.githubusercontent.com/62384659/122472771-ebaf5300-cfb8-11eb-8b5c-3e4390a26cb1.png)

**Desired State of the GetNighthawk.dev site**
Adjust the 'what is Nighthawk" component to cross the diagonal line. [Figma link](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=5046%3A0)

![Screenshot 2021-06-16 at 13 09 32](https://user-images.githubusercontent.com/62384659/122472817-f7027e80-cfb8-11eb-8a94-0cf92e99073b.png)

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Anita-ihuman** [comment]
@sayantan1413  would you like to t ake this up?

**Comment by sayantan1413** [comment]
@Anita-ihuman Yes I would like to take up this issue
