### ISSUE TITLE
[README] Need to add `Community Forum`

### ISSUE THREAD

**Issue by amino19** [layer5io/getnighthawk#148]
**Description**

<a href="https://github.com/layer5io/getnighthawk/blob/master/README.md">README.md</a> is the first file one should read when starting a new project. Our community launched `Discussion forum` for help seekers; needs to publish it officially on README.md for convenience.

### Screenshots

**Current behaviour:**
![image](https://user-images.githubusercontent.com/75872316/123441080-16209200-d5f1-11eb-8cac-0f82770161e6.png)

**Desired behaviour:**
![image](https://user-images.githubusercontent.com/75872316/123440623-9d213a80-d5f0-11eb-8ffd-87ba14c0159b.png)

**Note:**
Need to add only last line for `Community Forum`

**Environment:**
 - OS: any [e.g. Ubuntu]
 - Browser: any [e.g. Chrome, Safari]
 - Version: any [e.g. 22]
 - Device: any [e.g. laptop, iPhone 8]

---
**Reference:**
- Take reference to this <a href="https://github.com/layer5io/layer5/pull/1949">pull request</a>

**Comment by sayantan1413** [comment]
Link to the community Forum `https://discuss.layer5.io/`.

**Comment by amino19** [comment]
@sayantan1413 : Thanks for label, can you give a small shot. 😉

**Comment by sayantan1413** [comment]
@amino19 I can give it a shot but would you mind if I leave this issue for a new contributor then they would feel good solving this issue in their first shot. :)
(Though I am also a newbie but I have contributed some in this organization)

**Comment by Harshit-1999** [comment]
I would like take this task.
