### ISSUE TITLE
[Site] Dead link - Docs/Section1/overview

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#156]
**Current State of the GetNighthawk.dev site**
request release timings broken link on Docs/Section1/overview
(https://github.com/layer5io/getnighthawk/blob/master/docs/collections/_docs/really-using-getnighthawk.md)

**Desired State of the GetNighthawk.dev site**
Remove the broken link (anchor tag)

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by vinayaksh42** [comment]
@leecalcote I think we should move towards adding the docs as well as updating the FAQ and other content of the website

**Comment by AnshumanDhiman** [comment]
Hey @vinayaksh42 can I work on this issue.

**Comment by vinayaksh42** [comment]
> Hey @vinayaksh42 can I work on this issue.

Sure @AnshumanDhiman
