### ISSUE TITLE
[Site] Cropped off images 

### ISSUE THREAD

**Issue by warunicorn19** [layer5io/getnighthawk#158]
**Description**

The images used on https://getnighthawk.dev/ are cropped off.

**Expected Behavior**

These images seemed to be cut off at source so we're in need of better images to replace these.

**Screenshots**

<img width="875" alt="Screenshot 2021-08-10 at 12 20 58 PM" src="https://user-images.githubusercontent.com/53532328/128821986-15dc6520-d134-4925-98f0-acb8985676da.png">

<img width="793" alt="Screenshot 2021-08-10 at 12 20 18 PM" src="https://user-images.githubusercontent.com/53532328/128822034-357cc460-8d13-465d-81ed-be39f60b3b3f.png">

**Environment:**

- OS: MacOs
- Browser: Chrome
- Version: [e.g. 22]
- Device: [e.g. laptop, iPhone 8]

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by AnshumanDhiman** [comment]
Hi @warunicorn19 can I work on this issue

**Comment by AnshumanDhiman** [comment]
Can anyone provide the new images so that the old one's can be replaced by them as in the issue mentioned.

**Comment by warunicorn19** [comment]
@vinayaksh42 could you please provide some images that can be used, I'm not sure what images are supposed to be used.
