### ISSUE TITLE
[Site] Broken links 

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#166]
**Current State of the GetNighthawk.dev site**
Currently, the Run GetNighthawk link in the footer is not linked to anywhere
Docs link in footer opens in new tab although the page belongs within the website.

**Desired State of the GetNighthawk.dev site**

Run getnighthawk should be linked to Docs section 1 and the docs link should open in the same tab
---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by AnshumanDhiman** [comment]
can I work on this issue
