### ISSUE TITLE
[Site] Mobile responsiveness for Home page

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#168]
**Current State of the GetNighthawk.dev site**
![chrome_Ww5xyovfub](https://user-images.githubusercontent.com/54861487/130127413-a3f9e4e9-3bf7-447b-88b0-d75c49a05e26.png)

**Desired State of the GetNighthawk.dev site**
![chrome_1cgVpCqofN](https://user-images.githubusercontent.com/54861487/130127423-986e32c5-c592-4bfe-b288-ffa644ad200b.png)

The text needs to be center-aligned for both the sections

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by AnshumanDhiman** [comment]
Can I work on this @vinayaksh42
