### ISSUE TITLE
[Site] Text align and paragraph size mismatch

### ISSUE THREAD

**Issue by AnshumanDhiman** [layer5io/getnighthawk#170]
**Description**

The current landing home page of the getnighthawk have the paragraph font different in the starting and as the one mentioned below and the heading written as "Easing Management of Nighthawk Lifecycle " is Left aligned in the Mobile View.

**Expected Behavior**

The size of fonts of the paragraph tag must be same and the heading must be center aligned in Mobile View.

**Screenshots**

![2](https://user-images.githubusercontent.com/67755381/130677122-ec4e1792-efea-432b-a890-2a18b9bd7026.png)
![3](https://user-images.githubusercontent.com/67755381/130677131-09b4b7fc-45a5-4c7b-8240-9050d6eb8e91.png)
![4](https://user-images.githubusercontent.com/67755381/130677137-5abd98a5-4025-4535-9914-ca547436215c.png)

**Environment:**

- OS: [e.g. Ubuntu]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
- Device: [e.g. laptop, iPhone 8]

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by warunicorn19** [comment]
@AnshumanDhiman will you be taking this on?

**Comment by AnshumanDhiman** [comment]
Yes I will take this on

**Comment by warunicorn19** [comment]
😎 awesome!

**Comment by leecalcote** [comment]
Good stuff, @AnshumanDhiman 🙂

**Comment by AnshumanDhiman** [comment]
> Good stuff, @AnshumanDhiman

thank you @leecalcote 😊
