### ISSUE TITLE
Padding and Text align in getnighthawk mobile view

### ISSUE THREAD

**Issue by AnshumanDhiman** [layer5io/getnighthawk#173]
**Description**

For the Mobile View,
1. The paragraph in the "Why Getnighthawk" section is end to end on the sides.
2. The paragraph in the "Easing Management of the Nighthawk Lifecyle" is left aligned.

**Expected Behavior**

1. Add some padding in the "Why Getnighthawk" paragraph section.
2. Change the text align to center in the "Easing Management of the Nighthawk Lifecycle" paragraph section and add some padding there also 

**Screenshots**

![Screenshot_20210829-150830_Chrome](https://user-images.githubusercontent.com/67755381/131245986-cea07765-123c-4678-baa6-0c1b0521f2bb.jpg)
![Screenshot_20210829-150843_Chrome](https://user-images.githubusercontent.com/67755381/131245988-94c606c9-17fd-4fd5-9292-d8fcb506f80a.jpg)

**Environment:**

- OS: [e.g. Ubuntu]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
- Device: [e.g. laptop, iPhone 8]

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by vinayaksh42** [comment]
Nice catch @AnshumanDhiman, make sure that the desktop version remains the same

**Comment by AnshumanDhiman** [comment]
Yes @vinayaksh42 will keep in mind :)
