### ISSUE TITLE
[Site] Docs Section

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#175]
**Current State of the GetNighthawk.dev site**
Currently, we have 3 placeholder sections

**Desired State of the GetNighthawk.dev site**
The docs section can be further expanded to add the following sections:

1. Getting started/overview/installation
2. concepts/functionality/architecture
3. Community/about/mailing list/ meetings (same as smp - https://docs.google.com/document/d/1wiPiEoaaQgJ3E1lQF2tBIn1IblpUay0cHLjsWRcWV2o/edit)

The above sections can be constructed based on the content at
- https://github.com/envoyproxy/nighthawk
- Meshery Docs

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by AnshumanDhiman** [comment]
can I work on this @vinayaksh42

**Comment by warunicorn19** [comment]
@AnshumanDhiman would you still like to work on this?

**Comment by AnshumanDhiman** [comment]
Yes @warunicorn19 but I am not having the data which needs to be added into the website, like in the document form....

**Comment by akshitarora921** [comment]
@vinayaksh42 Can you please explain more?

**Comment by leecalcote** [comment]
Gents, you could export a few of the slides as SVGs from this deck - https://docs.google.com/presentation/d/1arewKYZuhkv7NGRZKx0w-7bQdS-ho-YSYJF0X32qfHo/edit# and incorporate into the docs. 👍

**Comment by Sonichigo** [comment]
can i work on this? @warunicorn19 @leecalcote

**Comment by YashKamboj** [comment]
@Sonichigo i think @akshitarora921 is already working on it

**Comment by akshitarora921** [comment]
Thank you, @Sonichigo. I am not working on this issue. You can take this up. ✌🏼

**Comment by warunicorn19** [comment]
@leecalcote could you please give some more insights on this? is there a need to create sub-sections like @vinayaksh42 has written in the issue above? or just incorporate svgs from the slide deck into the existing docs.

**Comment by leecalcote** [comment]
I think we're all set on the sections, but yes, could use some additional illustrations added to the docs by way of exporting a few of slides as SVGs and inserting into the docs.

**Comment by Sonichigo** [comment]
Hey @leecalcote is the presentation access removed? Have imported just 1-2 svg at most yet
