### ISSUE TITLE
Add Adaptive Load Control Deck to GetNighthawk website

### ISSUE THREAD

**Issue by navendu-pottekkat** [layer5io/getnighthawk#177]
**Current State of the GetNighthawk.dev site**

Anirban did an overview of adaptive load controllers in Nighthawk on September 10th's community meeting.

**Desired State of the GetNighthawk.dev site**

Add the slides to the GetNighthawk website.

Link to slides: https://docs.google.com/presentation/d/1uQBrocLLqudO-xKSVL38d8w9BXlNOLeB/edit?rtpof=true

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by l5io** [comment]
Completed?

**Comment by Sunnyio** [comment]
Hey @navendu-pottekkat  can i work on this?
