### ISSUE TITLE
Latency scale graph cutting in mobile view

### ISSUE THREAD

**Issue by AnshumanDhiman** [layer5io/getnighthawk#188]
**Description**

In the https://getnighthawk.dev/about the mobile view is having image's sides cropped off.

**Expected Behavior**

Some amount of padding must be given.

**Screenshots**

![Screenshot 2021-10-01 012529](https://user-images.githubusercontent.com/67755381/135522119-f97dfab9-26ea-4789-a0b8-a09271259c5e.jpg)

**Environment:**

- OS: [e.g. Ubuntu]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
- Device: [e.g. laptop, iPhone 8]

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by AnshumanDhiman** [comment]
can I work on this ?

**Comment by warunicorn19** [comment]
Sure @AnshumanDhiman

**Comment by anubhav201241** [comment]
Hey, @warunicorn19
A similar issue problem with the website is that the menu icon in mobile view is not aligned properly 

![image](https://user-images.githubusercontent.com/72249059/135726439-232406af-43fd-4a9d-be2d-57b0a456478b.png)

![image](https://user-images.githubusercontent.com/72249059/135726508-53dd3e46-5d20-4a9b-80bb-e736531e2878.png)

So can I work on this issue?

**Comment by warunicorn19** [comment]
@anubhav201241 I think this is being worked on in #189

**Comment by anubhav201241** [comment]
oh ok, thank you no problem!!
