### ISSUE TITLE
Navbar not responsive in any device view

### ISSUE THREAD

**Issue by PulkitSinghDev** [layer5io/getnighthawk#189]
**Description**

The website's navbar is not responsive and doesn't have a good UX, making the navbar less user responsive

**Expected Behavior**

- Hover Effects
- Well-aligned text
- Having it responsive on all device view

**Screenshots**

![image](https://user-images.githubusercontent.com/71369943/135563496-0c8504b4-a039-4295-bbd2-28523ac075ed.png)
![image](https://user-images.githubusercontent.com/71369943/135563570-e42b1526-500f-436e-a694-b5668a8482c4.png)
![image](https://user-images.githubusercontent.com/71369943/135563629-e234040f-4a2c-4811-baff-ce5ceb7b5cdd.png)

**Environment:**

- OS: [e.g. Ubuntu]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
- Device: [e.g. laptop, iPhone 8]

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by toth2000** [comment]
Looking into it.

**Comment by warunicorn19** [comment]
@toth2000 i think @PulkitSinghDev is already looking into this?

**Comment by PulkitSinghDev** [comment]
Yes, @warunicorn19, I am looking into this :)

**Comment by PulkitSinghDev** [comment]
you can assign it to me :)

**Comment by PulkitSinghDev** [comment]
and if possible, would like to include it in my Hacktoberfest contributions 😄

**Comment by warunicorn19** [comment]
Yeah for sure it will, if you could just put a comment down when you put in the PR for this.

**Comment by PulkitSinghDev** [comment]
sure!

**Comment by warunicorn19** [comment]
@PulkitSinghDev are there any updates on this?

**Comment by PulkitSinghDev** [comment]
hey @warunicorn19 , I am sorry but not getting much time for it, maybe you can assign it to someone else

**Comment by leecalcote** [comment]
@PulkitSinghDev thanks for letting us know.

**Comment by Abhijay007** [comment]
@leecalcote I want to work on this issue !!

**Comment by anirudh-bukka** [comment]
May I work on this too? (Is collaboration allowed?)

**Comment by Abhijay007** [comment]
> May I work on this too? (Is collaboration allowed?)

why not @anirudh-bukka you can go ahead with this, I will help you in the process !! let's close this issue 🚀 , ping me on slack !!
