### ISSUE TITLE
nighthawk-meshery image is cropped

### ISSUE THREAD

**Issue by Manish-210** [layer5io/getnighthawk#190]
**Description**

In the about and home section of https://getnighthawk.dev/ the image for nighthawk-meshery (https://getnighthawk.dev/assets/images/nighthawk-meshery.png) is cropped off, It should have been replaced.

**Expected Behavior**

https://getnighthawk.dev/assets/images/smp-standard.png This image has to placed there.

**Environment:**

- OS: Ubuntu
- Browser: Mozilla Firefox
- Version: 92.0
- Device: Laptop

---

**To Reproduce**

1. Go to https://getnighthawk.dev/about
2. Scroll down to end
3. See image at left

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Manish-210** [comment]
Can I work on this?

**Comment by warunicorn19** [comment]
Sure @Manish-210
