### ISSUE TITLE
Image issues in the getnighthawk homepage

### ISSUE THREAD

**Issue by AnshumanDhiman** [layer5io/getnighthawk#195]
**Description**

The image is not aligned properly with the supporting heading.

![err2](https://user-images.githubusercontent.com/67755381/135897513-d841f166-4d84-4d1f-b987-f05cbaa73707.jpg)

**Expected Behavior**

 Align the image and the supporting heading to the same level.

**Environment:**

- OS: [e.g. Ubuntu]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
- Device: [e.g. laptop, iPhone 8]

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by warunicorn19** [comment]
@AnshumanDhiman the first part of the issue already has an open issue.

**Comment by AnshumanDhiman** [comment]
@warunicorn19 well I thought size of the image should be increased for the time being. But I think its ok if we're changing the whole image. That's a lot better. I updated the issue.

**Comment by leecalcote** [comment]
@AnshumanDhiman there have been some site updates since this bug was filed. Will you confirm if this is still on open defect?

**Comment by AnshumanDhiman** [comment]
I checked it. The issue is solved. Let me close this issue
