### ISSUE TITLE
[Website] Refresh Nighthawk logos; Remove "GET" from all pages

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#200]
**Current Behavior**
The current set of Nighthawk logos say "GETNIGHTHAWK". These are being replaced with a set that says "NIGHTHAWK".

**Desired Behavior**
1. Remove "GET" from any of the descriptions of this project.
1. Replace old logos with new logos (attached)

The website will still be getnighthawk.dev, but the logos have all dropped the "Get".

**Kit**
- [nighthawk-brand-kit.zip](https://github.com/layer5io/layer5/files/7450213/nighthawk-brand-kit.zip)

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by toth2000** [comment]
Looking into this.
