### ISSUE TITLE
[Site] Unequal split of image and adjoining description on main page

### ISSUE THREAD

**Issue by kayceeDev** [layer5io/getnighthawk#206]
**Description**

The meshery nighthawk performance chart image is bigger than 50% of its container.

**Expected Behavior**

It should be adjusted to be 50% of its container.

**Screenshots**
<img width="2992" alt="Screen Shot 2021-11-18 at 1 42 41 PM" src="https://user-images.githubusercontent.com/42142223/142488079-76d4e035-030d-4aec-be12-7d7502bf0291.png">

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by leecalcote** [comment]
@kayceeDev can you take this on?

**Comment by leecalcote** [comment]
@Neilblaze is this an issue you can address?

**Comment by Neilblaze** [comment]
I don't see any such issue populating on my end, but when I zoom out to 25% (on my PC), only then, this actually become prominent. But yeah, if the CSS can be tweaked, then it can be restricted to it's 50% area-scope

**Comment by leecalcote** [comment]
@Neilblaze, good. Can you carry this forward?

**Comment by akshitarora921** [comment]
@leecalcote Can you assign this to me, please?
