### ISSUE TITLE
Vertical whitespace needed: top and bottom section margins should be symmetric

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#216]
**Description**

The FAQ section of the main page on https://getnighthawk.dev is missing whitespace to match that of other sections.

**Expected Behavior**
Top and bottom section margins should be symmetric.

**Screenshots**
<img width="736" alt="Screen Shot 2021-11-29 at 10 56 10 AM" src="https://user-images.githubusercontent.com/7570704/143910304-ba6ff8b3-c56d-4bde-95b1-d71637daa0df.png">

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Abusayid693** [comment]
@leecalcote I can fix this

**Comment by leecalcote** [comment]
@Abusayid693 that'd be great. Thank you.
