### ISSUE TITLE
Add newcomers-alert workflow

### ISSUE THREAD

**Issue by cpepper96** [layer5io/getnighthawk#221]
**Current Behavior**

This repo currently does not have the newcomer-alert workflow added. There is no automated process for notifying slack when a good newcomer issue has been added.

**Desired Behavior**

Add the newcomer-alert workflow to the repo.

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by cpepper96** [comment]
can someone assign this issue to me?

**Comment by theBeginner86** [comment]
@cpepper96 you are good to go 🚀

**Comment by theBeginner86** [comment]
I'm reopening this issue as I think it got closed by mistake.
