### ISSUE TITLE
Update slack.yml workflow

### ISSUE THREAD

**Issue by FidalMathew** [layer5io/getnighthawk#224]
**Current State:**
   Outdated slack.yml

**Desired State:**
   Updated repository with slack.yml  workflow

---
**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by theBeginner86** [comment]
Thank you @FidalMathew for opening this issue.

Actually, there was already one issue addressing the newcomers-alert workflow. Can you please modify this issue to address just the slack workflow?

**Comment by FidalMathew** [comment]
> 

Sure, I would like to work on this issue too!

**Comment by theBeginner86** [comment]
@FidalMathew 🚀

**Comment by leecalcote** [comment]
Teamwork!
