### ISSUE TITLE
Form for community mailing list

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#229]
This one was really for me to create a Google Group mailing list, which I believe we have now (see the mailing list section on the main page). Yes, you're right - we essentially want the same thing that we have on amp-spec.io and meshery.io. We essentially have that now, but are missing two things:

1. a text field to receive visitor's email address, so that they can subscribe to the community mailer. Example - https://smp-spec.io#subscribe
2. a formatting issue on https://getnighthawk.dev/subscribe. Margin is needed to separate the nav bar and prevent overlap:
<img width="471" alt="Screen Shot 2021-12-23 at 10 45 59 AM" src="https://user-images.githubusercontent.com/7570704/147269670-25a1c672-0233-4375-abd2-80e8e890fa20.png">

_Originally posted by @leecalcote in https://github.com/layer5io/getnighthawk/issues/44#issuecomment-1000419189_

**Comment by Abhijay007** [comment]
I want to work on this issue, please assign this issue to me !!

**Comment by theBeginner86** [comment]
@Abhijay007 🚀

**Comment by Abhijay007** [comment]
https://user-images.githubusercontent.com/64387054/147891575-fbd5f537-f66d-4206-bcb3-2065bc4bde14.mp4


@leecalcote I am done with the formatting, do it need to add anything else? can a open a pr for this now?

**Comment by leecalcote** [comment]
Looks pretty good, @Abhijay007. Yes.

Let's change our working structure to: when you're ready for feedback, pop open a PR. 👍

**Comment by Abhijay007** [comment]
> 

ok

**Comment by Abhijay007** [comment]
> Looks pretty good, @Abhijay007. Yes.
> 
> Let's change our working structure to: when you're ready for feedback, pop open a PR. 👍

ok
