### ISSUE TITLE
Fix link in the footer

### ISSUE THREAD

**Issue by debo19** [layer5io/getnighthawk#230]
**Description**
The link directs to https://getnighthawk.dev/docs/what-is-getnighthawk but the page doesn't exist.

**Expected Behavior**
The link should direct to https://getnighthawk.dev/docs/what-is-nighthawk/ 

**Screenshots**

![nighthawk](https://user-images.githubusercontent.com/85789734/147338718-38359520-8885-4b2f-ad30-ab5e2d76889f.jpg)

**Environment:**

- OS: [e.g. Ubuntu]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
- Device: [e.g. laptop, iPhone 8]

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Swapnil-Bhabal** [comment]
Kindly assign this task to me @debo19

**Comment by Swapnil-Bhabal** [comment]
#232 
Thats my PR on this issue @debo19  , i have made the required changes
Kindly review my PR, Thank you.

**Comment by ahmadateya** [comment]
I think this issue should be closed too.

I am looking for a small good first issue to start with, that's why I am leaving this comments :sweat_smile:

**Comment by leecalcote** [comment]
@ahmadateya here's one - https://github.com/meshery/meshery-nsm/issues/135

This link might be helpful in finding others - https://github.com/issues?q=is%3Aopen+is%3Aissue+archived%3Afalse+org%3Alayer5io+org%3Ameshery+org%3Aservice-mesh-performance+org%3Aservice-mesh-patterns+label%3A%22help+wanted%22+

**Comment by ahmadateya** [comment]
@leecalcote thank you :heart:
