### ISSUE TITLE
[Site] : Set the Open Graph image for the nighthawk site 

### ISSUE THREAD

**Issue by Abhijay007** [layer5io/getnighthawk#235]
**Current State of the GetNighthawk.dev site**

The nighthawk project doesn't have required OG (Opengraps) tags 

![image](https://user-images.githubusercontent.com/64387054/148590119-9fac9ab8-63e5-4eb4-8364-982fb7b828ce.png)

**Desired State of the GetNighthawk.dev site**

Add required og: tags for the image so that it has a preview image while sharing links associated with it on any social network or app that utilizes rich previews!!

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

Check out [this](https://www.freecodecamp.org/news/what-is-open-graph-and-how-can-i-use-it-for-my-website/#what-is-open-graph) article if you are not familiar with OpenGraph tags

**Comment by Vidyaa123** [comment]
@Abhijay007, I will work on this issue please, thanks

**Comment by leecalcote** [comment]
Thanks for this, @Abhijay007, @Vidyaa123 👍
