### ISSUE TITLE
Unhandled Exception in Output Transform

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#237]
**Description**

A performance test was invoked from Meshery UI with the following profile:

```
Endpoints: https://github.com/meshery/meshery
Load Generators: nighthawk
Test Run Duration: 15s
Concurrent Request: 2
Queries Per Second: 2
Service Mesh: nginx service mesh
```

The test seems to run, but crashes as output is transformed upon return to the user.

**Expected Behavior**

Test should complete and display results to the user.

**Logs**

```
time="2022-01-15T21:32:08Z" level=info msg="perf test with config: &{nginx service mesh_1642282328719  https://github.com/meshery/meshery 2 2 <nil> <nil> []  false 15s nighthawk 0    true 0 false  false 0s}" app=meshery
time="2022-01-15T21:32:09Z" level=info msg="starting test"
time="2022-01-15T21:32:09Z" level=info msg="listening to test events"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2e47743]

goroutine 302 [running]:
github.com/layer5io/nighthawk-go/pkg/client.Transform(0xc00113f950, 0x37992e4, 0x6, 0x0, 0x1, 0x0, 0x3ba7530, 0xc000d30c80)
	/go/pkg/mod/github.com/layer5io/nighthawk-go@v1.0.3/pkg/client/transform.go:142 +0x943
github.com/layer5io/meshery/helpers.NighthawkLoadTest(0xc0011e2000, 0xc00090dde8, 0xc00019c000, 0xc0005f8300, 0x1abedde0e1a59d13)
	/github.com/meshery/meshery/helpers/load_test_interface.go:411 +0xf85
github.com/layer5io/meshery/handlers.(*Handler).executeLoadTest(0xc000318140, 0x3b8b678, 0xc00019c000, 0xc0009a6700, 0xc0001c6b23, 0x24, 0xc0010e8320, 0x20, 0xc000b4e8a0, 0x12, ...)
	/github.com/meshery/meshery/handlers/load_test_handler.go:345 +0x1014
github.com/layer5io/meshery/handlers.(*Handler).loadTestHelperHandler.func2(0xc000318140, 0xc0009a6700, 0xc0001c6b23, 0x24, 0xc0010e8320, 0x20, 0xc000b4e8a0, 0x12, 0xc0001c6bdd, 0x24, ...)
	/github.com/meshery/meshery/handlers/load_test_handler.go:319 +0x111
created by github.com/layer5io/meshery/handlers.(*Handler).loadTestHelperHandler
	/github.com/meshery/meshery/handlers/load_test_handler.go:317 +0x685
```

#### Environment

- Host OS: Mac
- Meshery Server Version: stable-v0.6.0-rc-3
- Meshery Client Version: stable-v0.6.0-rc-3
- Platform:  Kubernetes

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
@gyohuangxin, is this an issue that you can investigate?

**Comment by leecalcote** [comment]
Thank you, @gyohuangxin 👍

**Comment by gyohuangxin** [comment]
I can reproduce this error with Meshery Server Version stable-v0.6.0-rc-3 and stable-v0.6.0-rc-4, but if I build a image from Meshery v0.6.0-rc-4 branch with `make docker` command and apply this test image to Meshery deployment:
```
          value: https://meshery.layer5.io
        image: gyohuang/meshery-test
        imagePullPolicy: Always
        name: meshery
```

Then it works to run performance test with nighthawk.
![image](https://user-images.githubusercontent.com/42127654/149926955-2bbf11ca-43dd-4e0c-9b23-eae5a3c72e19.png)

So I wonder what's the difference between released image and my test image?

**Comment by leecalcote** [comment]
@DelusionalOptimist, will you engage with @gyohuangxin here?

**Comment by DelusionalOptimist** [comment]
@gyohuangxin this might be happening due to inconsistency between the results produced by Nighthawk and expected by the transformer.
Meshery server still seems to be using the old version of getnighthawk which had the old transformer (combination of `nighthawk_output_transform` and some hacks in Go). While transforming results, the old transformer looks for the `h2` flag. However it was deprecated in later nighthawk versions - https://github.com/envoyproxy/nighthawk/blob/4d65b135a76faf34aa9e4914ec2ae10f327a21e0/api/client/options.proto#L150.
Here is the relevant code in the old transformer: https://github.com/layer5io/getnighthawk/blob/d1cf4cc42d66c29849097fc71e1b84203b28f2fe/pkg/client/transform.go#L142

Since the [getnighthawk](https://hub.docker.com/r/layer5/getnighthawk/tags) docker image was updated 2 months back and it has the newer version of `nighthawk_server` and `nighthawk_output_transform`, the results produced by it don't have the `h2` flag. Thus, the old transformer panics while looking for this in the returned results. 

I suggest making a new stable release of [getnighthawk](https://github.com/layer5io/getnighthawk) repository and then updating its version in Meshery server or meshery-perf (wherever transformation is desired) so that the newer transformer which is compatible with newer version of Nighthawk is used.

**Comment by gyohuangxin** [comment]
@DelusionalOptimist Thank you for the answer. It's the reason why I ask the difference of images release between getnighthawk and meshery. 
As I mentioned above, if I rebuild Meshery v0.6.0-rc-4 and re-deploy then it works, however, v0.6.0-rc-4 still use getnighthawk v1.0.3.  

https://github.com/meshery/meshery/blob/64c7097b5c1d73acf24fd1e054cbdac732356629/go.mod#L41 

But your commit to removed `h2` flag was later than v1.0.3, what confused me is how does it work? 

https://github.com/layer5io/getnighthawk/commit/5ab5cc3e9363a0bb4a00028bb82dd624d505600c#diff-a7da9d911d75d33ec208c4eb7716b2f07b71d55a569b2e66f0831706f8e17f8aL55

Anyway, we need a new stable release of getnightawk indeed, and update getnightawk version in Meshery go.mod.

**Comment by DelusionalOptimist** [comment]
> Thank you for the answer. It's the reason why I ask the difference of images release between getnighthawk and meshery.
As I mentioned above, if I rebuild Meshery v0.6.0-rc-4 and re-deploy then it works, however, v0.6.0-rc-4 still use getnighthawk v1.0.3.

Not sure @gyohuangxin... the published image and the image that you've built locally with `make docker` should work the same way. Also, the screenshot you shared in one of the comments is missing proper test result data so I think there would have been some error.

**Comment by gyohuangxin** [comment]
@DelusionalOptimist Thanks. The action we need now is to published a new getnighthawk release and image . After that, I will raise a PR to change this pointer in Meshery.  
@leecalcote Can you help with the new release of getnighthawk?

**Comment by leecalcote** [comment]
@gyohuangxin absolutely. Making a new release now....

**Comment by gyohuangxin** [comment]
@leecalcote @DelusionalOptimist The PR has been raised to upgrade getnighthawk version in meshery, please have a review. Thanks.

**Comment by gyohuangxin** [comment]
@DelusionalOptimist Unit Tests and build failed due to the same error "unknown field `H2` in struct literal", can you look at that? https://github.com/meshery/meshery/runs/4963356841?check_suite_focus=true
