### ISSUE TITLE
[Site] faq title arrows should be spaced apart

### ISSUE THREAD

**Issue by akshitarora921** [layer5io/getnighthawk#239]
#### Current Behavior
The meshery nighthawk faq title and arrow are adjacent to each other

#### Expected Behavior
It should be space apart and consistent irrespective to the faq title length
#### Screenshots/Logs
![image](https://user-images.githubusercontent.com/11087313/150305472-794b18b2-2153-47c6-a23a-03268ba4e862.png)

#### Contributor Resources

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
  - 🎨 Wireframes and designs for Nighthawk Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by akshitarora921** [comment]
Please assign this to me

**Comment by Abhijay007** [comment]
@akshitarora921 go ahead !! 🚀
