### ISSUE TITLE
[Question]: Regarding Font Size and Padding of Text

### ISSUE THREAD

**Issue by Sonichigo** [layer5io/getnighthawk#246]
**How can we help?**

Is the text formatting made in this way for the project? As for the first timers it looks a lot clustered. 

![image](https://user-images.githubusercontent.com/53110238/153126320-e6701ea5-29bd-4e47-8edc-5ed9cc377278.png)

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Abhijay007** [comment]
closed #246 via #251
