### ISSUE TITLE
[Docs]: Name of the given docs category

### ISSUE THREAD

**Issue by Sonichigo** [layer5io/getnighthawk#249]
**Current State:**
Performance Benchmarking is mentioned at top in docs of https://getnighthawk.dev/ in every doc.
![image](https://user-images.githubusercontent.com/53110238/153536299-e31ac630-e9c4-4d93-8d14-4cd7b424a2f5.png)

**Desired State:**
 The name of the given docs category should probably be used instead.

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Sunnyio** [comment]
I would like to do this.

**Comment by warunicorn19** [comment]
@Sunnyio i think @Sonichigo is already working on this, please feel free to look at other issues.

**Comment by Sunnyio** [comment]
Sure. No problem @warunicorn19 .
