### ISSUE TITLE
Make the sidebar of the docs page sticky.

### ISSUE THREAD

**Issue by YashKamboj** [layer5io/getnighthawk#252]
**Current Behavior**
The sidebar position is absolute

**Desired Behavior**
Make the sidebar of the docs page sticky.

---

**Resources**

**Alternatives / Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by ritesh-karankal** [comment]
Hello there! can I work on this issue?

**Comment by YashKamboj** [comment]
Go ahead!! @ritesh-karankal

**Comment by Mano-08** [comment]
Hey, may I give it a try.
do you not mean something like this
``````diff
- position: absolute ;
+ position: sticky ;
``````

**Comment by YashKamboj** [comment]
Yeah @Mano-08 But the issue is solved, you can look for issues around to work on

**Comment by Mano-08** [comment]
Oh, okay sure
