### ISSUE TITLE
[Docs] Sidebar in mobile view

### ISSUE THREAD

**Issue by debo19** [layer5io/getnighthawk#254]
**Current State of the GetNighthawk.dev site**
The button to open the sidebar on [Nighthawk Docs ](https://getnighthawk.dev/docs) is placed such that it covers the content on the page and its purpose isn't very clear.
<table>
<td>
<img width="262" alt="Screenshot 2022-02-22 at 2 39 46 PM" src="https://user-images.githubusercontent.com/85789734/155100245-32b9a0bd-9875-4087-bf0b-b55085660026.png">
</td>
<td>
<img width="255" alt="Screenshot 2022-02-22 at 2 40 26 PM" src="https://user-images.githubusercontent.com/85789734/155100290-a0595d93-f841-438b-9d5e-82ec19230855.png">
</td>
</table>

**Desired State of the GetNighthawk.dev site**
Preferably, move the button to the top-left corner. Could be converted into a semi-circle to show only a part of the button appearing from the edge.

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by debo19** [comment]
@YashKamboj @Abhijay007 Is either of you looking into this or is this an open issue?

**Comment by Abhijay007** [comment]
> @YashKamboj @Abhijay007 Is either of you looking into this or is this an open issue?

we are working on this one :)
