### ISSUE TITLE
[Website] Integrate Discussion Forum with Posts by Tag

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#280]
### Current State of the GetNighthawk.dev site
getnighthawk.dev does not integrate with its discussion forum (discuss.layer5.io). Ideally, each docs page will displays the most recent 10 discussion forum posts by tag name: "nighthawk".

See an example of this integration [in-action on this Meshery Docs page](https://docs.meshery.io/guides/mesheryctl). And [see this discussion](https://discuss.layer5.io/t/proposal-and-call-for-participation-building-the-community-leaderboard/1712/2) for more context.

See the [discuss.layer5.io design spec](https://docs.google.com/document/d/1MDdIZGr8cw_iyZD1H4G7k8AbcFJ79_4UhbKgGltfa7U/edit#heading=h.gqjd5dgruo7t) and the [moderating the community discussion forum docs](https://docs.google.com/document/d/1o4DydORiy4Cwe3UpbCg7TWGnt5ry7t-AXuddO2w0k0g/edit?pli=1#heading=h.mpw9xz2nzccu) for a list of other possibilities.

### Desired State of the GetNighthawk.dev site
Copy the work done in this [PR for Meshery Docs](https://github.com/meshery/meshery/pull/6773), and create a similar integration on getnighthawk.dev.

Use https://discuss.layer5.io/tag/nighthawk.json as the datasource.

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

---

- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by senali-d** [comment]
Fixed by PR: #282

**Comment by senali-d** [comment]
So I think we can close both the issues #280 and #281. Because It's already fixed.

**Comment by senali-d** [comment]
Done by #282
