### ISSUE TITLE
[CI] Create workflow to refresh list of discussion forum posts

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#281]
RELATED ISSUE: https://github.com/layer5io/getnighthawk/issues/280

#### Current Behavior
getnighthawk.dev does not integrate with its discussion forum (discuss.layer5.io). Ideally, each docs page will displays the most recent 10 discussion forum posts by tag name. Currently "nighthawk" is the only supported tag. See this related PR https://github.com/meshery/meshery/pull/6773 and this discussion https://discuss.layer5.io/t/proposal-and-call-for-participation-building-the-community-leaderboard/1712/2

#### Desired Behavior
A scheduled (cron) workflow should refresh the multiple lists of related discussion data files (json) on a daily basis.

#### Implementation
1. Checkout repo
1. Pull fresh list of related posts from:
    1. http://discuss.layer5.io/tag/nighthawk.json
1. Deposit data files here - https://github.com/layer5io/getnighthawk/tree/master/docs/_data/discuss
1. Autocommit fresh data files.

#### Acceptance Tests
1. Fresh list of related posts display in the Recent Discussions with "<tag>" Tag (e.g. https://docs.meshery.io/guides/mesheryctl)

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

---

- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by yash37158** [comment]
I would like to work on this issue @leecalcote

**Comment by leecalcote** [comment]
I'll tag in @asubedy to triage.

**Comment by senali-d** [comment]
@leecalcote I would like to contribute to this issue.

**Comment by leecalcote** [comment]
Thank you, @senali-d. There are some prime examples of this being done on meshery.io and docs.meshery.io that you might reference.

**Comment by senali-d** [comment]
Fixed by PR: #283

**Comment by senali-d** [comment]
done by #283

**Comment by senali-d** [comment]
done by #283
