### ISSUE TITLE
[Site] Design project logo and call for vote

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#29]
**Current Behavior**
The GetNighthawk is in need of a project logo.

**Desired Behavior**
1. A few logos are drafted, feedback is solicited and incorporated in to an iteration on the design. 
2. A vote for favorite design is called for.
3. Winning has a logo package created and includes a number of color, vertical, horizontal, stacked, black, white, RGB, CMYK versions.

**Comment by vinayaksh42** [comment]
<img width="555" alt="Screen Shot 2021-04-15 at 12 45 10 PM" src="https://user-images.githubusercontent.com/54861487/114974024-3fa99880-9e9f-11eb-8b44-2cdd09b4ec65.png">

Getnighthawk new logo

**Comment by vinayaksh42** [comment]
Closing this issue as the new logo has been decided.
