### ISSUE TITLE
Add "Star Meshery Repository ⭐ " button 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/getnighthawk#299]
Add a button on the HomePage to redirect the user to the [Meshery](https://github.com/meshery/meshery) Repository

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by thisiskaransgit** [comment]
@Saksham294  sure go ahead  :rocket:

**Comment by vednp** [comment]
Hey @thisiskaransgit is this open to work on?

**Comment by ashutosh887** [comment]
@thisiskaransgit 
Let me work on this now!

**Comment by thisiskaransgit** [comment]
@ashutosh887 @vednp, since we haven't heard back from @Saksham294, could any of you take care of this issue,

**Comment by vednp** [comment]
Sure I'd like to work on it

**Comment by thisiskaransgit** [comment]
@vednp, thanks you can see [meshery.io's](https://meshery.io) implementation for reference

**Comment by thisiskaransgit** [comment]
@Ghat0tkach, please take care of this

**Comment by ashutosh887** [comment]
Let me work on this @thisiskaransgit

**Comment by thisiskaransgit** [comment]
@ashutosh887, will you be able to resolve this pending issue quickly, with incorporating all the requests of previous PR?

**Comment by ashutosh887** [comment]
Yeah I think I can @thisiskaransgit

**Comment by ashutosh887** [comment]
Where do we want the button to be?

cc: @thisiskaransgit @leecalcote

**Comment by thisiskaransgit** [comment]
> Where do we want the button to be?
> 
Chek the previous PR, all the instructions are given

**Comment by thisiskaransgit** [comment]
> > Where do we want the button to be?
> > 

@ashutosh887 Chek the previous PR, all the instructions are given

**Comment by ashutosh887** [comment]
Do you mean #319 @thisiskaransgit  ?
