### ISSUE TITLE
[Docs]Error in Readme Links

### ISSUE THREAD

**Issue by Ghat0tkach** [layer5io/getnighthawk#301]
**Current State:**
Currently the  Layer5 community welcome link leads to incorrect reference .

**Desired State:**
It should lead to  https://layer5.io/community/handbook link

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Ghat0tkach** [comment]
p.s just saw even the welcome bot layer 5 community welcome guide link is invalid

**Comment by AryanSharma9917** [comment]
Hi @Ghat0tkach I would like to work on this issue could you please assign this to me
