### ISSUE TITLE
fix the visibility of slack and github logos

### ISSUE THREAD

**Issue by Rajivkumawat3** [layer5io/getnighthawk#311]
**Current Behavior**

<img width="28" alt="image" src="https://github.com/layer5io/getnighthawk/assets/122862213/c61033a2-1efc-42f3-8904-97cb124026c8">
<img width="48" alt="image" src="https://github.com/layer5io/getnighthawk/assets/122862213/19f39c18-b4bd-41ba-b719-607b05cfc750">

**Desired Behavior**
    Background will not be changed , only logos will be visiable after hover effect .
<img width="46" alt="image" src="https://github.com/layer5io/getnighthawk/assets/122862213/12093fb1-46bd-4d19-8c7f-ef070fb257c3">
<img width="48" alt="image" src="https://github.com/layer5io/getnighthawk/assets/122862213/4442a737-b84e-4a5f-a398-078bb70e626c">

 fix the visibility of slack and github logos on hover in the footer of https://getnighthawk.dev/      

**Resources**

**Alternatives / Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Rajivkumawat3** [comment]
I want to work on this issue . can you assign it to me

**Comment by bharathkalyans** [comment]
@Rajivkumawat3 are you currently working on this?

**Comment by Rajivkumawat3** [comment]
@Savio629  sir can you tell me reason , the pull request i made not showing its changes on netlify
