### ISSUE TITLE
Issue Template Updates for Figma link 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/getnighthawk#317]
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

```

**Acceptance Tests**
All references to Figma include the "open invite" link.

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by depleur** [comment]
Hey, I think I can work on this.

**Comment by Ghat0tkach** [comment]
**This issue is for the first-timers only**.Let's get some fresh and new contributors . Here is your chance newcomers 😉

**Comment by Chadha93** [comment]
Here you go @depleur

**Comment by depleur** [comment]
> Here you go @depleur 

Hey, I think it's best if we wait on these Figma template issues till we figure out what hyperlink needs to be attached as the issue still suggests a Meshery UI fix which isn't appropriate for a Layer5 repo.

**Comment by Chadha93** [comment]
> > Here you go @depleur
> 
> Hey, I think it's best if we wait on these Figma template issues till we figure out what hyperlink needs to be attached as the issue still suggests a Meshery UI fix which isn't appropriate for a Layer5 repo.

@depleur No need to wait. 

Use these 2 links for Nighthawk: (mention them separately).
1. Site - https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=5046-0&mode=design&t=UYVaGhic2LY8EXee-0

2. Meshery UI Nighthawk (Performance) -  https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=2-5814&mode=design&t=Gt14dmRRlpL09apZ-0

**Comment by abhijeetgauravm** [comment]
I think this issue has been fixed!

**Comment by abhijeetgauravm** [comment]
It's still not fixed....Can i fix it?
