### ISSUE TITLE
incorrect link in pr template in .github

### ISSUE THREAD

**Issue by Yana-Gupta** [layer5io/getnighthawk#326]
#### Current Behavior

The link to the `Signed Commit` is currently linking to the `Not Found` page in pr_template in github workflows [here](https://github.com/layer5io/getnighthawk/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1)
Now it is:
```
../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin
```
#### Expected Behavior

It should be changed to 
```
https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin
```

#### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---

#### Contributor Resources

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
  - 🎨 Wireframes and designs for Nighthawk Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by AryanSharma9917** [comment]
Hey @leecalcote, could you please assign this issue to me?

**Comment by hirentimbadiya** [comment]
go ahead @AryanSharma9917
