### ISSUE TITLE
The golangci-lint-action is present but the run command is missing 

### ISSUE THREAD

**Issue by VaibhavMalik4187** [layer5io/getnighthawk#330]
#### Current Behavior
The golangci-lint action was added in commit 5390f2da5637f61c2048c5153b8149c17100dd24 but the run command was never present. As a result, the action gets installed on the runner but never runs the linter.

![image](https://github.com/layer5io/getnighthawk/assets/34866732/a5bcbf9a-07d1-4ce3-8ca2-215f6b693636)

#### Expected Behavior
The linter must run in order to find lint errors.

---

#### Contributor Resources

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
  - 🎨 Wireframes and designs for Nighthawk Site in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by VaibhavMalik4187** [comment]
@leecalcote @MUzairS15 I'd like to fix this issue.

**Comment by leecalcote** [comment]
@VaibhavMalik4187 way to be! Sounds good. 👍

**Comment by VaibhavMalik4187** [comment]
I guess didn't do the homework properly. The lint job runs(just looked at the actions logs). My apologies for the trouble.
