### ISSUE TITLE
Copy feature Enhancement

### ISSUE THREAD

**Issue by kumarankit999** [layer5io/getnighthawk#337]
**Current Behavior**

If we want to copy the command for any OS Distribution, we have to select the command and then copy. Which might some time-consuming. 

**Desired Behavior**

We can change this by creating a copy button on the top-right corner so that if we want to copy the command, the only thing we do is click on the copy button. It will be very easy for developers.
---
![image](https://github.com/layer5io/getnighthawk/assets/111564362/df6cbfd0-4f11-4e13-b4bd-d1368061a1fa)

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)
- 🎨 Wireframes and designs for Nighthawk Site in [Figma](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?type=design&node-id=5046-0&mode=design&t=UYVaGhic2LY8EXee-0)
- Meshery UI Nighthawk (Performance) in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?type=design&node-id=2-5814&mode=design&t=Gt14dmRRlpL09apZ-0)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by shivang0-0** [comment]
Hi @kumarankit999, I believe I can add this enhancement, can you assign this issue to me?
Also, it would be very kind of you if you referred to the file to start looking for scope of enhancement.

**Comment by omesh-omg** [comment]
Hi @kumarankit999, can u update me on this issue if it is not yet done, can u please assign this to me ,I am looking for my first open source contribution

**Comment by Savio629** [comment]
Who's up to take up this issue?
@shivang0-0 @omesh-omg 
Also sorry for the late reply...

**Comment by omesh-omg** [comment]
Yes!

**Comment by omesh-omg** [comment]
Can I take it

**Comment by omesh-omg** [comment]
@Savio629
