### ISSUE TITLE
[Site] Navbar implementation for getnighthawk

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#35]
**Current Behavior**

Currently, the navbar is based on the meshery.io theme. 

**Desired Behavior**

needs to be implemented according to the following [figma ](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=2650%3A4236)mockup
Use a placeholder logo until the final getnighthawk logo is prepared.

![chrome_ziagJtEDEr](https://user-images.githubusercontent.com/54861487/107062156-fe41a080-67fe-11eb-9a4d-6aacabf30d15.png)

---
**Resources**

Refer to the 9th page of this [doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w/edit#) to get more info about color scheme and Typography

**Comment by chinmaym07** [comment]
@vinayaksh42 Can I knock this one too ?

**Comment by vinayaksh42** [comment]
sure @chinmaym07
