### ISSUE TITLE
[Site] Hero Section (get started)

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#36]
**Current Behavior**

The start section/hero section of getnighthawk is occupied by the previous following section:
![chrome_xuuDsn5aMa](https://user-images.githubusercontent.com/54861487/107063776-c5a2c680-6800-11eb-8975-42d9680d8036.png)

**Desired Behavior**

needs to be implemented according to the following [figma ](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=2650%3A4236)mockup
Use a placeholder logo until the final getnighthawk logo is prepared.

![chrome_jEx55cf2sK](https://user-images.githubusercontent.com/54861487/107063824-d2271f00-6800-11eb-9771-357756289b56.png)

---
**Resources**

Refer to the 9th page of this [doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w/edit#) to get more info about color scheme and Typography

**Comment by Grumpyyash** [comment]
Could I take this up?

**Comment by Nikhil-Ladha** [comment]
Sure @Grumpyyash . Go ahead 👍🏼
