### ISSUE TITLE
[Site] Nighthawk description sections

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#39]
**Current State of the GetNighthawk.dev site**
Currently, there is no proper section for a complete nighthawk description 

**Desired State of the GetNighthawk.dev site**
screenshot from figma for this section:
![chrome_jYOrVDR5f0](https://user-images.githubusercontent.com/54861487/107571046-5833d300-6c10-11eb-8dad-bfcbe9e301d4.png)

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Grumpyyash** [comment]
Can I try this? @vinayaksh42

**Comment by vinayaksh42** [comment]
> Can I try this? @vinayaksh42

sure go ahead
