### ISSUE TITLE
[Site] Why getNightHawk (card component)

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#40]
**Current State of the GetNighthawk.dev site**
There is a "Why Getnighthawk section already present on the current website

**Desired State of the GetNighthawk.dev site**
screenshot from Figma:
![chrome_OnTKAhdxeI](https://user-images.githubusercontent.com/54861487/107571243-a9dc5d80-6c10-11eb-8951-ae8bc3e4831e.png)
This will require the development of the card component with a transition effect.
---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by chinmaym07** [comment]
@vinayaksh42  Can I work on this .? 
Can you please let me know about the transition effect required on the cards ?

**Comment by vinayaksh42** [comment]
The card requires a hover effect of a background shadow. you can make a pr about it and we can discuss the effect.

**Comment by chinmaym07** [comment]
As far as I can observe on hover there should be a box-shadow , a bottom yellow coloured border , Yes I'll make a pr, Then I'll ask for improvements that can be made on that. thanks !!
