### ISSUE TITLE
[Site] Footer improvements 

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#42]
**Current Behavior**

Currently, the footer lacks alignment and proper placement of contents

**Desired Behavior**

Screenshot from Figma:
![chrome_ydzZIE5D4n](https://user-images.githubusercontent.com/54861487/107571940-98e01c00-6c11-11eb-89e3-438e7ee8060e.png)

---
**Resources**

**Alternatives / Additional Context**

**Comment by chinmaym07** [comment]
Hey Can I work on this .? @vinayaksh42

**Comment by vinayaksh42** [comment]
> Hey Can I work on this .? @vinayaksh42

Sure, Go ahead

**Comment by vinayaksh42** [comment]
refer to this link https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=2650%3A4236 for better design reference.

**Comment by vinayaksh42** [comment]
Hey @chinmaym07 if you are facing any issue regarding the setup of this repo or the actual issue itself, feel free to drop me a message on slack

**Comment by chinmaym07** [comment]
> Hey @chinmaym07 if you are facing any issue regarding the setup of this repo or the actual issue itself, feel free to drop me a message on slack

No@vinayaksh42  I have fixed the above issue ..will send the pr asap.
