### ISSUE TITLE
[Site] Newsletter signup 

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#43]
**Current State of the GetNighthawk.dev site**
Newsletter signup is not present on the current website

**Desired State of the GetNighthawk.dev site**
Screenshot from Figma:
![chrome_NUWiy6LkJn](https://user-images.githubusercontent.com/54861487/107572175-e78db600-6c11-11eb-9e4c-60a62725510a.png)
This section is supposed to be right above the footer

---
**Contributor Resources**
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md.
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Grumpyyash** [comment]
Can I try this? @vinayaksh42

**Comment by vinayaksh42** [comment]
> Can I try this? @vinayaksh42

sure
