### ISSUE TITLE
[Community] GitHub teams: two for contributors and another for maintainers

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#45]
The GetNighthawk Project will benefit from use of GitHub teams, so that those teams may be used for assigning reviewers.

1. [getnighthawk-contributors](https://github.com/orgs/layer5io/teams/getnighthawk-contributors) - collection of all GetNighthawk contributors
1. getnighthawk-ci-contributors - collection of backend and CI-focused contributors
1. getnighthawk-site-contributors - collection of frontend-focused contributors
3. getnighthawk-maintainers - collection of project maintainers

Hierarchy of teams (and permissions):

1) site contributor structure
- getnighthawk-contributors - triage
  - getnighthawk-site-contributors - triage
     - getnighthawk-maintainers - write

2) ci contributor structure
- getnighthawk-contributors - triage
  - getnighthawk-ci-contributors - triage
    - getnighthawk-maintainers - write

**Comment by leecalcote** [comment]
@mum4k @oschaaf does this look good to you?

**Comment by mum4k** [comment]
Looks good to me @leecalcote.

**Comment by oschaaf** [comment]
+1

**Comment by leecalcote** [comment]
Thank you, gents. Teams created.
