### ISSUE TITLE
[Docs] Contributing: website contributing instructions needed

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#46]
**Current State:**
The CONTRIBUTING.md in this repo needs is missing some information and instructions specific to this project.

**Desired State:**
The CONTRIBUTING.md in this repo needs to be updated information about what framework and plugins that the GetNighthawk website uses. It also needs updated with instructions for how to contribute and how to build the GetNighthawk website.

Resource: See the [GetNightHawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w/edit#) for details

**Comment by Ruth-ikegah** [comment]
Nice Taking this up!

**Comment by leecalcote** [comment]
😀
