### ISSUE TITLE
[Project] GitHub Issue templates: need updated to be GetNighthawk-specific

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#47]
The GH issue templates - https://github.com/layer5io/getnighthawk/tree/master/.github/ISSUE_TEMPLATE - need to be updated with details and links specific to the GetNighthawk project.

**Comment by leecalcote** [comment]
@Grumpyyash?

**Comment by akashprasher** [comment]
can I do this task?

**Comment by Josephchinedu** [comment]
@leecalcote can @akashprasher take this

**Comment by leecalcote** [comment]
That would be great, yes. 👍

**Comment by akashprasher** [comment]
Thanks, @leecalcote, can you tell me what needs to change and what to add? I'll do it.
