### ISSUE TITLE
[Site] clean up of index.html

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#53]
**Current State of the GetNighthawk.dev site**
Currently, we have a lot of code snippets in the index.html that are not in match with the Figma design mockup

**Desired State of the GetNighthawk.dev site**
Requires a clean up of the index.html with a proper comparison with the design mockup

Figma link for reference: https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=2650%3A4236

Future goals related to this issue:

- Removal of the unused images and assets
- Removal of the unused CSS and scss files

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Grumpyyash** [comment]
Can I try this?

**Comment by vinayaksh42** [comment]
@Grumpyyash sure, feel free to message me in case of confusion regarding what to keep and what to remove
