### ISSUE TITLE
Custom nighthawk actions

### ISSUE THREAD

**Issue by kumarabd** [layer5io/getnighthawk#62]
**Description**

Two different actions that need to be created:

Setup Environment action:
The action would do the following tasks:
- Setup dependencies for building the project such as bazel,gcc etc..
- Setup git credentials with tokens for cloning the repository.

Build and publish action:
The action would do the following tasks:
- Clones the specified nighthawk version
- Builds the project for client, server and test_server.
- Create a release in this repository for the corresponding version.
- Publish the build artifacts to this release.
- The artifact should follow the naming convention mentioned here -  https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w/edit#

**Environment:**

- OS: [e.g. Ubuntu]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
- Device: [e.g. laptop, iPhone 8]

---

[Optional] **To Reproduce**

[Optional] **Additional Context**

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by leecalcote** [comment]
Done, @kumarabd?

**Comment by kumarabd** [comment]
yes this has been done.
