### ISSUE TITLE
[Site] Hero section missing a component

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#63]
**Current State of the GetNighthawk.dev site**
Hero section currently looks like this:-
![chrome_w6xFScbTuO](https://user-images.githubusercontent.com/54861487/108982936-565c1c00-76b4-11eb-8952-1bc8363874a5.png)

**Desired State of the GetNighthawk.dev site**
Hero section needs to look like this:- 
![chrome_Nmwum1YxOL](https://user-images.githubusercontent.com/54861487/108982978-6247de00-76b4-11eb-8b40-aaa9bf97a6f7.png)

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Grumpyyash** [comment]
Sure, I will do it soon
