### ISSUE TITLE
Update the 'Why GetNighthawk' section on the home page

### ISSUE THREAD

**Issue by Grumpyyash** [layer5io/getnighthawk#72]
Currently, the 'Why GetNighthawk' section on the homepage is not according to the Figma design.

![why-getnighthawk-wrong](https://user-images.githubusercontent.com/62200066/109960237-90f63200-7d0e-11eb-80e1-52166bdb60cf.png)

The section should be modified according to the Figma design given  - https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs?node-id=2650%3A4236

![why-getnighthawk](https://user-images.githubusercontent.com/62200066/109960444-c7cc4800-7d0e-11eb-9997-90bd0acfb250.png)

**Environment:**

- OS: [e.g. Ubuntu]
- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]
- Device: [e.g. laptop, iPhone 8]

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by vinayaksh42** [comment]
Thanks for opening this issue
