### ISSUE TITLE
[Site] Actual FAQ questions and answers

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#78]
**Current State of the GetNighthawk.dev site**
Duplicate answers in the FAQ section

**Desired State of the GetNighthawk.dev site**
Unique questions and answers requires

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by vinayaksh42** [comment]
@leecalcote 
We require answers for the following 2 questions:

-  Will nighthawk_client and nighthawk_server still be supported?
-  What projects are related to GetNighthawk?

**Comment by Jashpatel1** [comment]
@leecalcote @Anita-ihuman some help required here.

**Comment by Anita-ihuman** [comment]
Can I take this up?

**Comment by leecalcote** [comment]
@oschaaf I wonder if you have suggestions here on specific FAQs for Nighthawk.

**Comment by Anita-ihuman** [comment]
> * Will nighthawk_client and nighthawk_server still be supported?

@vinayaksh42 I can't seem to find an answer that suits this question.
Could use a helping hand.

**Comment by vinayaksh42** [comment]
> > * Will nighthawk_client and nighthawk_server still be supported?
> 
> @vinayaksh42 I can't seem to find an answer that suits this question.
> Could use a helping hand.

@leecalcote, can you assist us in getting the actual FAQ content so that the dummy text can be replaced.

**Comment by leecalcote** [comment]
+ @layer5io/getnighthawk-maintainers

**Comment by DelusionalOptimist** [comment]
**"What value is GetNighthawk as an individual project adding to Nighthawk?"**
* Aimed at alligning and making Nighthawk compatible with the SMP spec.
* A Go native wrapper for using Nighthawk.
* Enables `mesheryctl` to do multi version lifecycle management of Nighthawk.
* A vehicle for creating and publishing Nighthawk extensions.
* Publishes Nighthawk artifacts compatible with multiple OS and CPU architectures.
* Provides a container with ready to use Nighthawk binaries.
* A logo and a website.
* A community of contributors.
* An audience within CNCF projects
* A shared spotlight on KubeCon stage.
* Enables easy Nighthawk adoption.

And much more to come in future... :smile:

**Comment by vinayaksh42** [comment]
> > * Will nighthawk_client and nighthawk_server still be supported?
> 
> @vinayaksh42 I can't seem to find an answer that suits this question.
> Could use a helping hand.

@Anita-ihuman do you want to take this issue, we now have the FAQ content

**Comment by khanjasir90** [comment]
@leecalcote @Jashpatel1 can I work on this?

**Comment by warunicorn19** [comment]
@khanjasir90 go ahead, I think @Anita-ihuman is a bit busy now.

**Comment by khanjasir90** [comment]
@warunicorn19  great! can i get the answers to FAQ question.

**Comment by warunicorn19** [comment]
@vinayaksh42 ^^^

**Comment by warunicorn19** [comment]
This is one of them I think: https://github.com/layer5io/getnighthawk/issues/78#issuecomment-912003186

**Comment by Abhijay007** [comment]
I want to work on this issue? is anyone already working on this ??

**Comment by navendu-pottekkat** [comment]
1. Will nighthawk_client and nighthawk_server still be supported?

Yes, GetNighthawk will publish the Nighthawk binaries which can be dowloaded directly or used through a Docker image.

2. What projects are related to GetNighthawk?

Meshery, the service mesh management plane uses Nighthawk as a load generator for running performance tests. Meshery uses the Docker image published by GetNighthawk to run Nighthawk.

The Service Mesh Performance project is also closely related to GetNighthawk as it defines a standard for capturing these performance test configurations and results.

**Comment by Abhijay007** [comment]
> 1. Will nighthawk_client and nighthawk_server still be supported?
> 
> Yes, GetNighthawk will publish the Nighthawk binaries which can be dowloaded directly or used through a Docker image.
> 
> 2. What projects are related to GetNighthawk?
> 
> Meshery, the service mesh management plane uses Nighthawk as a load generator for running performance tests. Meshery uses the Docker image published by GetNighthawk to run Nighthawk.
> 
> The Service Mesh Performance project is also closely related to GetNighthawk as it defines a standard for capturing these performance test configurations and results.

thanks for this :)
