### ISSUE TITLE
[Site] About Section-Single page layout

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#80]
**Current State of the GetNighthawk.dev site**
Empty about page

**Desired State of the GetNighthawk.dev site**
Requires a single page layout/design for the about section.
@austinogiza 

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by leecalcote** [comment]
@vineethvanga18 any progress to report here?

// @Grumpyyash @chinmaym07

**Comment by vineethvanga18** [comment]
I was working on docs page layout

**Comment by leecalcote** [comment]
Oops. I commented the wrong issue. Please do self-assign the other issue, if you haven't already.

**Comment by Anita-ihuman** [comment]
I will like to take on this issue
