### ISSUE TITLE
[Site] Link fix for all the Buttons

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#81]
**Current State of the GetNighthawk.dev site**
A few buttons are not linked to any link

**Desired State of the GetNighthawk.dev site**
Requires linking of all the buttons to proper links
 - Join Us - https://docs.google.com/document/d/18hYemFKK_PC_KbT_TDBUgb0rknOuIhikkRxer4_bv4Q/edit#
 - Need link for Ask Us button
 - Need link for Learn More button

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Grumpyyash** [comment]
I think Ask Questions can be led to community or contact for now if specifics are not yet created? @leecalcote

**Comment by vinayaksh42** [comment]
@Grumpyyash we plan to link it with the discussion form that is currently being created

**Comment by Grumpyyash** [comment]
So, we will wait till then!

**Comment by vinayaksh42** [comment]
**Buttons can be linked to**
coming soon -> get started (link to documentation)
Learn more -> https://layer5.io/projects/getnighthawk
Ask Questions -> https://discuss.layer5.io/
@leecalcote any suggestions on this?

**Comment by soham4abc** [comment]
I am working on this issue if possible pls assign.
