### ISSUE TITLE
[Site] Multiple burger menu in Mobile view for Docs Page

### ISSUE THREAD

**Issue by vinayaksh42** [layer5io/getnighthawk#88]
**Current State of the GetNighthawk.dev site**
Currently, there are 2 burger menus when we switch to the mobile view on the Docs page.

**Desired State of the GetNighthawk.dev site**
As discussed in the March 29th 2021 website meeting: Addition of a floating menu for the Docs section. In a similar way as it is on https://reactjs.org/docs/getting-started.html Any other suitable way of doing this can also be approached.

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by adithyaakrishna** [comment]
Hey @vinayaksh42 , Can I work on this?
Along with this, the texts in on the site aren't aligned properly in Mobile view. Will fix that too with this🚀

**Screenshot:**
![image](https://user-images.githubusercontent.com/23498248/114752007-7b474400-9d73-11eb-982d-d77e29597baa.png)

**Comment by vinayaksh42** [comment]
@adithyaakrishna sure, I will assign this issue to you

For the Mobile view problem you can create a new issue and work under it.

**Comment by vinayaksh42** [comment]
hey, @adithyaakrishna are you still working on this issue? 

Feel free to contact me on slack in case you are facing any block while implementing the new changes.

**Comment by sudo-NithishKarthik** [comment]
Hey, I would like to take up this issue 😃

**Comment by Jashpatel1** [comment]
> Hey, I would like to take up this issue 😃

Sure, please go ahead

**Comment by sudo-NithishKarthik** [comment]
I am sorry @Jashpatel1 , i am busy with some work . Is it fine if i take some time ? its fine with me if anyone else is interested in taking up this issue ✌🏽

**Comment by kaushambisharma** [comment]
can i take up this issue?

**Comment by adithyaakrishna** [comment]
Yes sure @kaushambisharma 💯

**Comment by leecalcote** [comment]
@kaushambisharma's on the job! 😄

**Comment by vinayaksh42** [comment]
Hi , @kaushambisharma are you still working on this issue?
Feel free to reach out on Slack in case you are facing any blockers

**Comment by kaushambisharma** [comment]
@vinayaksh42 yes i am, will certainly do :)

**Comment by vinayaksh42** [comment]
> @vinayaksh42 yes i am, will certainly do :)

Hey @kaushambisharma are you still working on this issue?

**Comment by AnshumanDhiman** [comment]
if anyone's not working on this issue can I work on this ? @vinayaksh42 @leecalcote

**Comment by shubham-tyagi** [comment]
should I work on this @warunicorn19, or any newcomer should ?

**Comment by vedant-kakde** [comment]
@shubham-tyagi  You can work on this issue 🚀

**Comment by msaini0r** [comment]
@shubham-tyagi are you working on this issue? Otherwise, I can start working on this?

**Comment by shubham-tyagi** [comment]
Hey @msaini0r thanks for stepping up, I was caught up in other issues.

**Comment by leecalcote** [comment]
@msaini0r any progress to speak of?

**Comment by msaini0r** [comment]
You will have a pr by tomorrow. @leecalcote

**Comment by msaini0r** [comment]
@leecalcote I am working on this issue. When I am trying to change the CSS for the navigation bar, it is changing for the whole mobile view not just for the docs section. Just wanted to confirm this issue is only for the docs section or for the whole mobile view to make a new floating navigation bar? 

Below gif is just a sample.

![screen-capture](https://user-images.githubusercontent.com/87536360/147888859-4db43d09-acff-4f3c-a600-aa4d7b4ad8da.gif)

**Comment by leecalcote** [comment]
@vinayaksh42 can confirm.

**Comment by vinayaksh42** [comment]
Hi @msaini0r, For this issue we actually want to change the docs navigation menu and not the website's navigation menu. Basically the navigation menu that is used for going from one section of the documentation to the other. Right now, when we switch to mobile view in Docs section, We get two burger menus. One for the website navigation and one for the docs navigation. We want to change the docs navigation burger menu to a different format so that we have two distinct navigation menus when in mobile view (Docs page). I hope this clears up your doubt, feel free to message me on Slack if you require more information

**Comment by msaini0r** [comment]
@leecalcote @shubham-tyagi I am unassigning myself, I am not able to solve this issue.

**Comment by akshitarora921** [comment]
@vinayaksh42 @leecalcote I think we should put all the options in the main navbar.

**Comment by adithyaakrishna** [comment]
@anirudh-bukka Would you like to give this a try?

**Comment by anirudh-bukka** [comment]
> @anirudh-bukka Would you like to give this a try?

@adithyaakrishna , I have mostly will have my Finals and Labs in a week, so I am not sure if I will be able to spend time on this issue. But I will let you know and work on this if they are postponed.

**Comment by Sunnyio** [comment]
I would like to give it a shot.

**Comment by shubham-tyagi** [comment]
Thanks @Sunnyio, for taking this up.
