### ISSUE TITLE
[Site] Use new logo

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#92]
**Current State of the GetNighthawk.dev site**
The site currently has a placeholder logo. The official project logo can now be found here - https://github.com/layer5io/layer5/issues/1780

**Desired State of the GetNighthawk.dev site**
The site should use this new logo.

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by Anita-ihuman** [comment]
Can i take this issue?

**Comment by vinayaksh42** [comment]
@Anita-ihuman Sure, That would be great
