### ISSUE TITLE
[Site] Project logo revision

### ISSUE THREAD

**Issue by leecalcote** [layer5io/getnighthawk#95]
**Current State of the GetNighthawk.dev site**
The GetNighthawk logo has been revised. The logo on the site needs updated.

**Desired State of the GetNighthawk.dev site**
New logo is here - https://layer5.io/brand/getnighthawk-brand-kit.zip

---

**Contributor Resources**

- See the [Contributing to getnighthawk.dev Website](https://github.com/layer5io/getnighthawk/blob/master/CONTRIBUTING.md)
- See the Project Site section of [GetNighthawk project doc](https://docs.google.com/document/d/1lHfMo4iIx2WXFZIspfHyxTsPR1T63_2IV5NUkgxoo0w)

**Comment by vinayaksh42** [comment]
@Anita-ihuman would you like to work on this issue?

**Comment by Anita-ihuman** [comment]
Yea i would

**Comment by Anita-ihuman** [comment]
was there an update to the logo? because the new logo link provided looks exactly like the previous one.

**Comment by leecalcote** [comment]
@Anita-ihuman it's subtle, but the new one can be see here - https://layer5.io/projects/getnighthawk.
